SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\01-CreateDB.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\01-CreateDB.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\02-CreateDBObjects.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\02-CreateDBObjects.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\03-CreateDBTriggers.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\03-CreateDBTriggers.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-01-lkSampleType-SampleType.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-01-lkSampleType-SampleType.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-02-Properties-Area.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-02-Properties-Area.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-02-Daycare.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-02-Daycare.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-03-BloodPbResults-BloodTestResults.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-03-BloodPbResults-BloodTestResults.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-03-lkUnits-Units.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-03-lkUnits-Units.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-04-BloodPbResults-Lab.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-04-BloodPbResults-Lab.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-04-lkMedia-Medium.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-04-lkMedia-Medium.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-05-lkActionStatus-ActionStatus.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-05-lkActionStatus-ActionStatus.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-05-lkChildStatus-PersonStatus.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-05-lkChildStatus-PersonStatus.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-06-lkCleanupStatus-CleanupStatus.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-06-lkCleanupStatus-CleanupStatus.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-07-lkDataReview-ReviewStatus.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-07-lkDataReview-ReviewStatus.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-08-lkConstType-ConstructionType.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-08-lkConstType-ConstructionType.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-09-lkCondition-Condition.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-09-lkCondition-Condition.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-10-lkContactType-ContactType.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-10-lkContactType-ContactType.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-11-lkDataSource-DataSource.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-11-lkDataSource-DataSource.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-12-lkEthnicBackground-Ethnicity.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-12-lkEthnicBackground-Ethnicity.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-13-lkFlag-Flag.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-13-lkFlag-Flag.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-14-lkPropertyLinkType-PropertyLinkType.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-14-lkPropertyLinkType-PropertyLinkType.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-15-lkFrequency-Frequency.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-15-lkFrequency-Frequency.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-16-lkMethod-Method.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-16-lkMethod-Method.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-17-lkPrimLanguage-Language.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-17-lkPrimLanguage-Language.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-18-lkReleaseStatus-ReleaseStatus.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-18-lkReleaseStatus-ReleaseStatus.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-19-lkSamplePurpose-SamplePurpose.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-19-lkSamplePurpose-SamplePurpose.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-20-Children-Person.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-20-Children-Person.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-21-Families-PhoneNumberType.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-21-Families-PhoneNumberType.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-22-Families-PhoneNumber.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-22-Families-PhoneNumber.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-23-Properties-Property.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-23-Properties-Property.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-24-Families-Family.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-24-Families-Family.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-25-FamilyPropertyLink-FamilytoProperty.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-25-FamilyPropertyLink-FamilytoProperty.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-26-Questionnaires-QuestionnaireDataSource.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-26-Questionnaires-QuestionnaireDataSource.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-27-Questionnaires-Questionnaire.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-27-Questionnaires-Questionnaire.txt -d LCCHPTestImport
SQLCMD.EXE -E -i C:\temp\lCCHP\TestedMigrationScripts\Migration-28-ChildFamilyLink-PersontoFamily.sql -o C:\temp\lCCHP\TestedMigrationScripts\OUTPUT\Migration-28-ChildFamilyLink-PersontoFamily.txt -d LCCHPTestImport
