#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\01-CreateDB.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\01-CreateDB.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\02-CreateDBObjects.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\02-CreateDBObjects.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\03-CreateDBTriggers.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\03-CreateDBTriggers.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\ListRowsInEachTable.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\ListRowsInEachTable.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-01-lkSampleType-SampleType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-01-lkSampleType-SampleType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-02-BloodPbResults-Lab.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-02-BloodPbResults-Lab.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-02-DayCare.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-02-DayCare.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-02-Hobby.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-02-Hobby.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-02-Properties-Area.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-02-Properties-Area.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-03-BloodPbResults-BloodTestResults.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-03-BloodPbResults-BloodTestResults.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-03-DayCare.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-03-DayCare.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-03-lkUnits-Units.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-03-lkUnits-Units.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-04-Hobby.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-04-Hobby.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-04-lkMedia-Medium.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-04-lkMedia-Medium.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-05-lkActionStatus-ActionStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-05-lkActionStatus-ActionStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-05-lkChildStatus-PersonStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-05-lkChildStatus-PersonStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-05-Properties-Area.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-05-Properties-Area.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-06-BloodPbResults-BloodTestResults.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-06-BloodPbResults-BloodTestResults.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-06-lkCleanupStatus-CleanupStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-06-lkCleanupStatus-CleanupStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-07-lkDataReview-ReviewStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-07-lkDataReview-ReviewStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-07-lkUnits-Units.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-07-lkUnits-Units.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-08-lkConstType-ConstructionType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-08-lkConstType-ConstructionType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-09-lkCondition-Condition.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-09-lkCondition-Condition.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-10-lkChildStatus-PersonStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-10-lkChildStatus-PersonStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-10-lkContactType-ContactType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-10-lkContactType-ContactType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-11-lkContactType-ContactType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-11-lkContactType-ContactType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-11-lkDataSource-DataSource.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-11-lkDataSource-DataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-12-lkEthnicBackground-Ethnicity.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-12-lkEthnicBackground-Ethnicity.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-12-lkMedia-Medium.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-12-lkMedia-Medium.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-13-lkActionStatus-ActionStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-13-lkActionStatus-ActionStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-13-lkFlag-Flag.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-13-lkFlag-Flag.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-14-lkCleanupStatus-CleanupStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-14-lkCleanupStatus-CleanupStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-14-lkPropertyLinkType-PropertyLinkType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-14-lkPropertyLinkType-PropertyLinkType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-15-lkDataSource-DataSource.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-15-lkDataSource-DataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-15-lkFrequency-Frequency.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-15-lkFrequency-Frequency.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-16-lkDataReview-ReviewStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-16-lkDataReview-ReviewStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-16-lkMethod-Method.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-16-lkMethod-Method.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-17-lkEthnicBackground-Ethnicity.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-17-lkEthnicBackground-Ethnicity.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-17-lkPrimLanguage-Language.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-17-lkPrimLanguage-Language.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-18-lkReleaseStatus-ReleaseStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-18-lkReleaseStatus-ReleaseStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-19-lkFlag-Flag.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-19-lkFlag-Flag.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-19-lkSamplePurpose-SamplePurpose.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-19-lkSamplePurpose-SamplePurpose.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-20-Children-Person.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-20-Children-Person.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-20-lkPropertyLinkType-PropertyLinkType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-20-lkPropertyLinkType-PropertyLinkType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-21-Families-PhoneNumberType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-21-Families-PhoneNumberType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-21-lkFrequency-Frequency.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-21-lkFrequency-Frequency.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-22-Families-PhoneNumber.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-22-Families-PhoneNumber.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-22-lkMethod-Method.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-22-lkMethod-Method.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-23-lkPrimLanguage-Language.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-23-lkPrimLanguage-Language.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-23-Properties-Property.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-23-Properties-Property.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-24-Families-Family.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-24-Families-Family.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-24-lkReleaseStatus-ReleaseStatus.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-24-lkReleaseStatus-ReleaseStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-25-FamilyPropertyLink-FamilytoProperty.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-25-FamilyPropertyLink-FamilytoProperty.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-25-lkSamplePurpose-SamplePurpose.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-25-lkSamplePurpose-SamplePurpose.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-26-Children-Person.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-26-Children-Person.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-26-Questionnaires-QuestionnaireDataSource.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-26-Questionnaires-QuestionnaireDataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-27-Families-PhoneNumberType.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-27-Families-PhoneNumberType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-27-Questionnaires-Questionnaire.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-27-Questionnaires-Questionnaire.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-28-ChildFamilyLink-PersontoFamily.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-28-ChildFamilyLink-PersontoFamily.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-28-Families-PhoneNumber.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-28-Families-PhoneNumber.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-29-Properties-Property.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-29-Properties-Property.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-30-Families-Family.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-30-Families-Family.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-31-FamilyPropertyLink-FamilytoProperty.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-31-FamilyPropertyLink-FamilytoProperty.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-32-Questionnaires-QuestionnaireDataSource.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-32-Questionnaires-QuestionnaireDataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-33-Questionnaires-Questionnaire-ErrorCorrection.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-33-Questionnaires-Questionnaire-ErrorCorrection.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-33-Questionnaires-Questionnaire-PostErrorCorrection.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-33-Questionnaires-Questionnaire-PostErrorCorrection.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-34-ChildFamilyLink-PersontoFamily.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-34-ChildFamilyLink-PersontoFamily.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-35-CleanupLeadValues.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-35-CleanupLeadValues.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-36-RemoveNullLastNameAndPersonID.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-36-RemoveNullLastNameAndPersonID.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-37-SelectPersonTable.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-37-SelectPersonTable.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Tested\Migration-38-Consolidateto1Table.sql -o D:\DBSpace\DB\MigrationScripts\Tested\OUTPUT\Migration-38-Consolidateto1Table.txt -d LCCHPImport
