SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\01-CreateDB.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\01-CreateDB.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\03-CreateDBTriggers.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\03-CreateDBTriggers.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\ListRowsInEachTable.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\ListRowsInEachTable.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-01-lkSampleType-SampleType.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-01-lkSampleType-SampleType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-02-BloodPbResults-Lab.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-02-BloodPbResults-Lab.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-03-DayCare.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-03-DayCare.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-04-Hobby.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-04-Hobby.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-05-Properties-Area.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-05-Properties-Area.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-06-BloodPbResults-BloodTestResults.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-06-BloodPbResults-BloodTestResults.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-07-lkUnits-Units.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-07-lkUnits-Units.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-08-lkConstType-ConstructionType.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-08-lkConstType-ConstructionType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-09-lkCondition-Condition.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-09-lkCondition-Condition.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-10-lkChildStatus-PersonStatus.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-10-lkChildStatus-PersonStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-11-lkContactType-ContactType.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-11-lkContactType-ContactType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-12-lkMedia-Medium.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-12-lkMedia-Medium.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-13-lkActionStatus-ActionStatus.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-13-lkActionStatus-ActionStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-14-lkCleanupStatus-CleanupStatus.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-14-lkCleanupStatus-CleanupStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-15-lkDataSource-DataSource.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-15-lkDataSource-DataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-16-lkDataReview-ReviewStatus.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-16-lkDataReview-ReviewStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-17-lkEthnicBackground-Ethnicity.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-17-lkEthnicBackground-Ethnicity.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-19-lkFlag-Flag.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-19-lkFlag-Flag.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-20-lkPropertyLinkType-PropertyLinkType.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-20-lkPropertyLinkType-PropertyLinkType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-21-lkFrequency-Frequency.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-21-lkFrequency-Frequency.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-22-lkMethod-Method.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-22-lkMethod-Method.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-23-lkPrimLanguage-Language.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-23-lkPrimLanguage-Language.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-24-lkReleaseStatus-ReleaseStatus.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-24-lkReleaseStatus-ReleaseStatus.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-25-lkSamplePurpose-SamplePurpose.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-25-lkSamplePurpose-SamplePurpose.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-26-Children-Person.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-26-Children-Person.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-27-Families-PhoneNumberType.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-27-Families-PhoneNumberType.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-28-Families-PhoneNumber.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-28-Families-PhoneNumber.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-29-Properties-Property.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-29-Properties-Property.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-30-Families-Family.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-30-Families-Family.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-31-FamilyPropertyLink-FamilytoProperty.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-31-FamilyPropertyLink-FamilytoProperty.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-32-Questionnaires-QuestionnaireDataSource.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-32-Questionnaires-QuestionnaireDataSource.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-33-Questionnaires-Questionnaire-ErrorCorrection.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-33-Questionnaires-Questionnaire-ErrorCorrection.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-33-Questionnaires-Questionnaire-PostErrorCorrection.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-33-Questionnaires-Questionnaire-PostErrorCorrection.txt -d LCCHPImport
SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-34-ChildFamilyLink-PersontoFamily.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-34-ChildFamilyLink-PersontoFamily.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-35-CleanupLeadValues.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-35-CleanupLeadValues.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-36-RemoveNullLastNameAndPersonID.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-36-RemoveNullLastNameAndPersonID.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-37-SelectPersonTable.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-37-SelectPersonTable.txt -d LCCHPImport
#SQLCMD.EXE  -E -i D:\DBSpace\DB\MigrationScripts\Migration-38-Consolidateto1Table.sql -o D:\DBSpace\DB\MigrationScripts\OUTPUT\Migration-38-Consolidateto1Table.txt -d LCCHPImport
